class BadgeDefinition {
  const BadgeDefinition({
    required this.key,
    required this.title,
    required this.description,
    required this.metric,
    required this.target,
    required this.tier,
  });

  final String key;
  final String title;
  final String description;
  final BadgeMetric metric;
  final int target;
  final String tier;
}

enum BadgeMetric {
  lifetimeCompletions,
  lifetimePhotoCompletions,
  totalXp,
}

class BadgeCatalog {
  const BadgeCatalog._();

  static const List<BadgeDefinition> all = [
    BadgeDefinition(
      key: 'first_step',
      title: 'First Step',
      description: 'Complete your first activity.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 1,
      tier: 'bronze',
    ),
    BadgeDefinition(
      key: 'streak_starter',
      title: 'Streak Starter',
      description: 'Reach 7 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 7,
      tier: 'bronze',
    ),
    BadgeDefinition(
      key: 'steady_builder',
      title: 'Steady Builder',
      description: 'Reach 30 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 30,
      tier: 'silver',
    ),
    BadgeDefinition(
      key: 'relentless',
      title: 'Relentless',
      description: 'Reach 100 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 100,
      tier: 'gold',
    ),
    BadgeDefinition(
      key: 'photo_journaler',
      title: 'Photo Journaler',
      description: 'Log 10 photo completions.',
      metric: BadgeMetric.lifetimePhotoCompletions,
      target: 10,
      tier: 'silver',
    ),
    BadgeDefinition(
      key: 'xp_novice',
      title: 'XP Novice',
      description: 'Earn 250 XP.',
      metric: BadgeMetric.totalXp,
      target: 250,
      tier: 'bronze',
    ),
    BadgeDefinition(
      key: 'xp_veteran',
      title: 'XP Veteran',
      description: 'Earn 1000 XP.',
      metric: BadgeMetric.totalXp,
      target: 1000,
      tier: 'gold',
    ),
    BadgeDefinition(
      key: 'completions_3',
      title: 'Momentum',
      description: 'Reach 3 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 3,
      tier: 'bronze',
    ),
    BadgeDefinition(
      key: 'completions_15',
      title: 'Builder',
      description: 'Reach 15 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 15,
      tier: 'silver',
    ),
    BadgeDefinition(
      key: 'completions_50',
      title: 'Committed',
      description: 'Reach 50 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 50,
      tier: 'gold',
    ),
    BadgeDefinition(
      key: 'completions_75',
      title: 'Stone Wall',
      description: 'Reach 75 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 75,
      tier: 'gold',
    ),
    BadgeDefinition(
      key: 'completions_150',
      title: 'Unshakeable',
      description: 'Reach 150 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 150,
      tier: 'platinum',
    ),
    BadgeDefinition(
      key: 'completions_250',
      title: 'Machine',
      description: 'Reach 250 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 250,
      tier: 'platinum',
    ),
    BadgeDefinition(
      key: 'completions_400',
      title: 'Mythic Tempo',
      description: 'Reach 400 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 400,
      tier: 'legendary',
    ),
    BadgeDefinition(
      key: 'photo_3',
      title: 'Snapshot',
      description: 'Log 3 photo completions.',
      metric: BadgeMetric.lifetimePhotoCompletions,
      target: 3,
      tier: 'bronze',
    ),
    BadgeDefinition(
      key: 'photo_25',
      title: 'Visual Log',
      description: 'Log 25 photo completions.',
      metric: BadgeMetric.lifetimePhotoCompletions,
      target: 25,
      tier: 'silver',
    ),
    BadgeDefinition(
      key: 'photo_50',
      title: 'Storyteller',
      description: 'Log 50 photo completions.',
      metric: BadgeMetric.lifetimePhotoCompletions,
      target: 50,
      tier: 'gold',
    ),
    BadgeDefinition(
      key: 'photo_100',
      title: 'Archivist',
      description: 'Log 100 photo completions.',
      metric: BadgeMetric.lifetimePhotoCompletions,
      target: 100,
      tier: 'platinum',
    ),
    BadgeDefinition(
      key: 'photo_200',
      title: 'Cinematic',
      description: 'Log 200 photo completions.',
      metric: BadgeMetric.lifetimePhotoCompletions,
      target: 200,
      tier: 'legendary',
    ),
    BadgeDefinition(
      key: 'xp_100',
      title: 'XP Spark',
      description: 'Earn 100 XP.',
      metric: BadgeMetric.totalXp,
      target: 100,
      tier: 'bronze',
    ),
    BadgeDefinition(
      key: 'xp_500',
      title: 'XP Climber',
      description: 'Earn 500 XP.',
      metric: BadgeMetric.totalXp,
      target: 500,
      tier: 'silver',
    ),
    BadgeDefinition(
      key: 'xp_1500',
      title: 'XP Engine',
      description: 'Earn 1500 XP.',
      metric: BadgeMetric.totalXp,
      target: 1500,
      tier: 'gold',
    ),
    BadgeDefinition(
      key: 'xp_2500',
      title: 'XP Core',
      description: 'Earn 2500 XP.',
      metric: BadgeMetric.totalXp,
      target: 2500,
      tier: 'platinum',
    ),
    BadgeDefinition(
      key: 'xp_5000',
      title: 'XP Titan',
      description: 'Earn 5000 XP.',
      metric: BadgeMetric.totalXp,
      target: 5000,
      tier: 'legendary',
    ),
    BadgeDefinition(
      key: 'xp_8000',
      title: 'XP Nova',
      description: 'Earn 8000 XP.',
      metric: BadgeMetric.totalXp,
      target: 8000,
      tier: 'legendary',
    ),
    BadgeDefinition(
      key: 'completions_600',
      title: 'Evergreen',
      description: 'Reach 600 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 600,
      tier: 'legendary',
    ),
    BadgeDefinition(
      key: 'completions_800',
      title: 'Clockwork',
      description: 'Reach 800 total completions.',
      metric: BadgeMetric.lifetimeCompletions,
      target: 800,
      tier: 'legendary',
    ),
    BadgeDefinition(
      key: 'photo_350',
      title: 'Visual Veteran',
      description: 'Log 350 photo completions.',
      metric: BadgeMetric.lifetimePhotoCompletions,
      target: 350,
      tier: 'legendary',
    ),
    BadgeDefinition(
      key: 'photo_500',
      title: 'Gallery Master',
      description: 'Log 500 photo completions.',
      metric: BadgeMetric.lifetimePhotoCompletions,
      target: 500,
      tier: 'legendary',
    ),
  ];
}
