const List<String> motivationalQuotes = [
  'Small steps still outrun standing still.',
  'You kept a promise to yourself today.',
  'Discipline is your quiet superpower.',
  'Progress loves consistency more than speed.',
  'You showed up, and that changes everything.',
  'Momentum starts with one honest check-in.',
  'Your future is built in moments like this.',
  'Done today is stronger than perfect tomorrow.',
  'You are training trust in yourself.',
  'One completed day is a vote for your goals.',
  'Consistency is confidence in motion.',
  'You proved you can follow through.',
  'Tiny wins compound into remarkable results.',
  'You are becoming the person you planned for.',
  'Keep stacking days; the story writes itself.',
  'Discipline feels small until it feels unstoppable.',
  'You moved forward, and forward counts.',
  'This is what self-respect looks like.',
  'Your streak is a mirror of your courage.',
  'Today done. Tomorrow ready.',
  'The habit is getting stronger than excuses.',
  'You just made tomorrow easier.',
  'Effort repeated becomes identity.',
  'Another day completed, another doubt removed.',
  'You are collecting proof, not promises.',
  'Every check-in sharpens your edge.',
  'Your standard just got higher.',
  'You did the hard part: beginning.',
  'Keep your word, keep your power.',
  'You are building a life that answers back.',
  'Greatness is mostly ordinary days done well.',
  'You stayed loyal to the plan today.',
  'Action beats intention every single time.',
  'You turned motivation into a system.',
  'Today counts, even if it felt small.',
  'You are stronger than your old patterns.',
  'The streak is not luck; it is character.',
  'Your pace is working. Keep it.',
  'Completion is confidence deposited.',
  'You are mastering the boring and winning big.',
  'Another brick placed. The wall is rising.',
  'You moved with purpose today.',
  'Success whispers through repeated choices.',
  'You kept the agreement with your future self.',
  'You are harder to stop than yesterday.',
  'The gap closes one completed day at a time.',
  'Your routine is becoming your advantage.',
  'You completed the day; the day did not beat you.',
  'Steady is a superpower.',
  'You are not guessing anymore; you are executing.',
  'Today was proof that you can do hard things.',
  'Your commitment is louder than your mood.',
  'You made progress inevitable today.',
  'You chose growth on purpose.',
  'Another day aligned with your goals.',
  'You are writing a reputation you can trust.',
  'Consistency made another appearance.',
  'You showed discipline when no one was watching.',
  'This is how long games are won.',
  'You did not wait for perfect conditions.',
  'One more day completed, one less day doubting.',
  'You are becoming impossible to derail.',
  'Execution is your new default.',
  'Your progress is no longer negotiable.',
  'You kept moving, and that is elite behavior.',
  'The habit held. So did you.',
  'You honored your priorities today.',
  'Your future self just said thank you.',
  'You made discipline look natural.',
  'Another strong day on the board.',
  'You are building results before they are visible.',
  'Good days are built, not found.',
  'You beat hesitation with action.',
  'Progress is your new comfort zone.',
  'You just reinforced a winning loop.',
  'Completion is the language of serious people.',
  'You handled today like a pro.',
  'The plan survived the day. You did that.',
  'Your focus is paying rent now.',
  'You made momentum non-negotiable.',
  'Another day where you chose who you are.',
  'You are stacking evidence of capability.',
  'Your effort is becoming automatic excellence.',
  'You did it tired, and that matters most.',
  'You are teaching yourself reliability.',
  'Small finish lines create big futures.',
  'Your standards are rising in real time.',
  'You showed range: discipline over comfort.',
  'Today finished. Progress secured.',
  'You are building a streak and a mindset.',
  'The hardest part keeps getting easier for you.',
  'You are not behind. You are building.',
  'You just made consistency look simple.',
  'Your actions are speaking louder than your doubts.',
  'You earned this momentum.',
  'The win is real because the work is real.',
  'You showed up with intention and finished strong.',
  'Another completed day. Another layer of grit.',
  'Your goals are getting less optional every day.',
  'You are becoming the person who finishes.',
  'You made today count. That is the whole game.',
  'You kept the chain alive, and chains change lives.',
  'Quiet progress is still powerful progress.',
  'Another completed day, another stronger baseline.',
  'You chose effort over excuses again.',
  'Your routine just earned another stripe.',
  'You are proving consistency is learnable.',
  'Today was a deposit in your confidence account.',
  'You are training discipline, not waiting for mood.',
  'Completion turns dreams into data.',
  'You pushed the needle forward on purpose.',
  'You are becoming dependable to yourself.',
  'Another done day, another doubt retired.',
  'You made a hard choice easy through repetition.',
  'Consistency is your unfair advantage now.',
  'You showed up with standards, not excuses.',
  'Progress just got another witness: you.',
  'Today is complete, and so is your commitment.',
  'You are building leverage one day at a time.',
  'A completed day is a confidence multiplier.',
  'You kept your focus when comfort called.',
  'Your momentum survived another test.',
  'You are writing discipline into muscle memory.',
  'Another day aligned, another future upgraded.',
  'You did not drift; you directed.',
  'This win is small, and that is why it scales.',
  'You are becoming predictable in the best way.',
  'You made the plan real again today.',
  'Each completed day is a vote against quitting.',
  'You earned peace by finishing what mattered.',
  'You are no longer hoping; you are executing.',
  'Today obeyed your priorities.',
  'The streak grows where excuses shrink.',
  'You proved commitment can be calm and steady.',
  'Another day complete, another level unlocked within.',
  'You did the reps that most people skip.',
  'Your consistency is becoming undeniable.',
  'You moved from intention to evidence again.',
  'You finished the day stronger than you started.',
  'This is what durable progress feels like.',
  'You are building grit with clean execution.',
  'Another completed day, another reason to trust yourself.',
  'You made action your answer today.',
  'You chose momentum over delay.',
  'Progress answered because you showed up.',
  'You turned discipline into daily rhythm.',
  'You are becoming hard to distract from your goals.',
  'You did what mattered, not just what was easy.',
  'Another check-in, another ceiling raised.',
  'Your effort today just reduced tomorrow’s friction.',
  'You are building a life that reflects your values.',
  'Completion is your new signature.',
  'You carried the standard through the day.',
  'You are turning ordinary days into extraordinary totals.',
  'Another day done means another excuse expired.',
  'You are becoming fluent in follow-through.',
  'You chose structure, and structure chose results.',
  'Your discipline is compounding quietly.',
  'Another completed day: proof over promises.',
  'You stayed on mission and finished clean.',
  'You put points on the board again.',
  'You honored the process, and it honored you back.',
  'You kept moving even without applause.',
  'Another day complete, another identity reinforced.',
  'You handled resistance and kept going.',
  'The streak is growing because you are growing.',
  'You protected your priorities like they matter.',
  'You are becoming your own strongest evidence.',
  'Another day completed with intention and grit.',
  'You did not need perfect, only consistent.',
  'You proved progress can be practiced daily.',
  'Your habits are beginning to carry you.',
  'Another day delivered. Momentum maintained.',
  'You chose long-term pride over short-term comfort.',
  'You made the hard option your normal option.',
  'Your follow-through is getting sharper.',
  'Another completed day, another boundary moved.',
  'You are building endurance for your goals.',
  'You showed that discipline can be quiet and relentless.',
  'Today’s completion is tomorrow’s confidence.',
  'You turned one more maybe into a done.',
  'Another day where your actions matched your values.',
  'You are creating reliability from repetition.',
  'You chose progress before comfort again.',
  'Your standards held under pressure.',
  'Another completed day means your trajectory improved.',
  'You kept the promise and kept the pace.',
  'You are building momentum that remembers.',
  'You showed discipline even when it was inconvenient.',
  'Another day complete. Identity upgraded.',
  'You made excellence feel ordinary today.',
  'You kept moving with purpose and precision.',
  'Your commitment survived another day.',
  'Another check mark, another future unlocked.',
  'You gave your goals real-world support today.',
  'You are turning consistency into inevitability.',
  'You finished strong, and strong is repeatable.',
  'Another day complete. Keep stacking.',
  'You made discipline look effortless through practice.',
  'You are becoming the person your goals require.',
  'Repetition is not boring; it is how legends are built.',
  'You did not flinch. You finished.',
  'Another day you chose discipline over delay.',
  'The version of you who quits is getting further away.',
  'You built the habit before the results arrived.',
  'Your goals are watching and they like what they see.',
  'You moved before motivation showed up, and that is everything.',
  'You are closing the gap between vision and reality.',
  'Another day where who you are matches what you said.',
  'You made the unglamorous look purposeful.',
  'Your work ethic just clocked in and delivered.',
  'One more completed day, one less thing left to chance.',
  'You are building a track record no one can fake.',
  'You executed. That is rarer than talent.',
  'You are the reason progress keeps happening.',
  'You showed up again. The scoreboard sees it.',
  'Another clean rep. Another stronger version.',
  'You are turning resistance into routine.',
  'You did not just survive today. You advanced.',
  'The excuses had no room. You filled it with action.',
  'You are converting intention into a body of work.',
  'Discipline is a decision you made again today.',
  'You are making the goal feel less like a destination and more like home.',
  'Habits are built in the quiet moments you just lived.',
  'Today you were your own coach, opponent, and champion.',
  'You moved with patience and still arrived ahead.',
  'Another day finished. Another proof of principle.',
  'You are collecting days that compound into character.',
  'Every repetition is rehearsing your best self.',
  'You picked effort over ease, and effort always wins longer.',
  'You are doing the work the outcome requires.',
  'Your standards are no longer negotiable, and it shows.',
  'You outran doubt again today.',
  'The only streak that matters kept going.',
  'You did not negotiate with the day. You led it.',
  'You made the plan the priority, not the mood.',
  'Another completed cycle, another earned reward.',
  'Progress needs witnesses. You just became one.',
  'You added to the record today. Keep it clean.',
  'Your future is reading these check-ins and smiling.',
  'One more day of not letting yourself down.',
  'You are writing a story worth telling.',
  'The best version of you keeps showing up.',
  'Another day handled. You make this look like a lifestyle.',
  'You are disciplined before you feel like it. That is mastery.',
  'You are building the thing most people only dream about.',
  'You earned the rest that comes after this.',
  'You picked the hard right over the easy wrong again.',
  'Your consistency is your most honest self-portrait.',
  'You gave today what it needed. Nothing borrowed, nothing owed.',
  'Another day. Another layer. Another you.',
  'You are proving that showing up is the whole skill.',
  'You ran your race at your pace and finished.',
  'The task asked for effort. You gave it character.',
  'You chose the long way because you know it leads somewhere.',
  'No shortcuts, no skips, no apologies.',
  'You answered today\'s question with action.',
  'Your dedication is becoming its own kind of talent.',
  'You kept the engine on when coasting was an option.',
  'You made completion your non-negotiable again.',
  'Every day you finish is a flag planted in your future.',
  'Your commitment survived the chaos and came out clean.',
  'You did what was required even when it felt optional.',
  'You are building proof that the plan actually works.',
  'Another day that confirms: you are built different.',
  'You did the thing when the thing was hard.',
  'Your output today was an act of self-respect.',
  'You delivered. Again.',
  'The habit is alive and well because you protected it.',
  'You turned a calendar day into a personal record.',
  'You are the most consistent force in your own story.',
  'You rose, you ran your race, you finished.',
  'Today, discipline won. It usually does when you show up.',
  'You are not chasing greatness anymore. You are building it.',
  'You made forward progress your only acceptable direction.',
  'Your effort today created options for tomorrow.',
  'Another mark on the wall. The wall is full of wins.',
  'You kept the deal with yourself and collected the interest.',
  'You are months ahead of where doubt said you would be.',
  'Every completed day is a door you opened for yourself.',
  'You chose action like it was the only language you speak.',
  'You moved the mission forward today. That is all it takes.',
];

const List<String> celebrationQuotes = [
  'You did not just keep pace. You set one.',
  'Twelve hidden wins found. Legendary focus.',
  'You turned a year into a masterpiece of consistency.',
  'This is what long-term discipline looks like in full color.',
  'You built a vault of proof and unlocked it.',
  'Few start this. Fewer finish this. You did both.',
  'Your patience became power.',
  'You did not chase luck. You built certainty.',
  'A full set of hidden victories. Iconic work.',
  'You turned quiet effort into a loud milestone.',
  'The finish line moved because you arrived stronger.',
  'This win is rare because your commitment was rare.',
  'You kept showing up until excellence became normal.',
  'A year of discipline now has a trophy to match.',
  'You made consistency feel inevitable.',
  'This is the kind of win people remember.',
  'You did not break the streak. You broke your ceiling.',
  'Twelve secrets found, one identity confirmed: finisher.',
  'Your long game just paid in full.',
  'Respect. This is elite follow-through.',
];